NAMESPACE: 'default'
K8S_REPLICAS: '1'
K8S_MAX_UNAVAIL: '1'
K8S_MAX_SURGE: '1'
K8S_REQ_MEM: '64Mi'
K8S_REQ_CPU: '100m'
K8S_LIMIT_MEM: '128Mi'
K8S_LIMIT_CPU: '150m'
AUTOSCALE_MIN_REPLICA: '1'
AUTOSCALE_MAX_REPLICA: '2'
AUTOSCALE_CPU_PERCENTAGE: '50'
DOCKER_APP_IMAGE: 'public.ecr.aws/y3z0f7y7/display'
APP_LOCATION: 'app/*'
CONTAINER_PORT: 8080