apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    name: myingress
spec:
  ingressClassName: nginx
  rules:
  - host: local.com
    http:
      paths:
      - backend:
          service:
            name: user-service
            port:
              number: 8081
        path: /register
        pathType: Prefix
      - backend:
          service:
            name: user-service
            port:
              number: 8081
        path: /authenticate
        pathType: Prefix
      - backend:
          service:
            name: game-service
            port:
              number: 8082
        path: /score
        pathType: Prefix
      - backend:
          service:
            name: game-service
            port:
              number: 8082
        path: /score/?(.*)
        pathType: Prefix
      - backend:
          service:
            name: display-service
            port:
              number: 8080
        path: /
        pathType: Prefix
